### ISSUE TITLE
不要自动跳转内网

### ISSUE THREAD

**Issue by afc163** [ant-design/antd-library#1]
提示一下，用户点击跳转如何？

**Comment by nikogu** [comment]
现在有提示，增加一步确认，用户其实也不知道这个内外网的区别是什么，反而还要思考到底要不要点确认呢～点不点呢～不是很有必要，暂时不加了。--海纳

**Comment by afc163** [comment]
另外，外网有 say.a****y.net 的请求。

**Comment by nikogu** [comment]
@afc163 那是我判断内外网的技术手段。。。没关系吧 🐒 ...

**Comment by nikogu** [comment]
就是访问内网的一个js，访问不到就说明在外网。。

**Comment by afc163** [comment]
OK
